---
- block:
    - name: ensure datadog agent is absent
      apt:
        name: datadog-agent={{ datadog_agent_version }}
        state: absent
        update_cache: yes

    - name: remove new datadog key from apt-key
      apt_key:
        id: d75cea17048b9acbf186794b32637d44f14f620e 
        keyserver: "keyserver.ubuntu.com"
        state: absent

    - name: remove old datadog key from apt-key
      apt_key: 
        id: c7a7da52
        keyserver: "keyserver.ubuntu.com"
        state: absent

    - name: cleanup datadog-agent related files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ datadog_legacy_config_path }}"
        - "{{ datadog_config_path }}"
        - "/var/log/datadog"
  become: true