---
- block:
    - name: ensure new datadog apt-key is added
      apt_key:
        id: a2923dff56eda6e76e55e492d3a80e30382e94de 
        keyserver: "keyserver.ubuntu.com"
        state: present

    - name: ensure datadog repository is up-to-date
      apt_repository:
        repo: "{{ datadog_apt_repo }}"
        state: present
        update_cache: yes

    - block:
        - name: check current running datadog-agent version
          shell: "dpkg -s datadog-agent | grep Version -m 1 | awk '{print $2}'"
          register: installed_dd_agent_version

        - assert:
            that:
              - installed_dd_agent_version.stdout == "{{ datadog_agent_version }}"
      rescue:
        - name: ensure pinned version of datadog agent is installed
          apt:
            name: "datadog-agent={{ datadog_agent_version }}"
            state: present
            update_cache: yes
            force: "{{ datadog_agent_allow_downgrade }}"

    - name: ensure example files are deleted
      command: 'find {{ item }} -name "*.example" -type f -delete'
      with_items:
        - "{{ datadog_legacy_config_path }}"
        - "{{ datadog_config_path }}"
      ignore_errors: yes

  become: true

- name: configure datadog agent
  include: configured.yml

- name: ensure datadog-agent is running
  service:
    name: datadog-agent
    state: started
    enabled: yes
  become: yes