---
- block:
    - name: ensure new datadog apt-key is added
      apt_key:
        id: a2923dff56eda6e76e55e492d3a80e30382e94de 
        keyserver: "keyserver.ubuntu.com"
        state: present

    - name: ensure datadog repository is up-to-date
      apt_repository:
        repo: "{{ datadog_apt_repo }}"
        state: present
        update_cache: yes

    - block:
        - name: check current running datadog-agent version
          shell: "dpkg -s datadog-agent | grep Version -m 1 | awk '{print $2}'"
          register: installed_dd_agent_version

        - assert:
            that:
              - installed_dd_agent_version.stdout == "{{ datadog_agent_version }}"
      rescue:
        - name: ensure pinned version of datadog agent is installed
          apt:
            name: "datadog-agent={{ datadog_agent_version }}"
            state: present
            update_cache: yes
            force: "{{ datadog_agent_allow_downgrade }}"

    - name: find example files in conf.d dir
      shell: "ls {{ datadog_config_path }}/conf.d/*.example"
      register: delete_list
      ignore_errors: yes

    - name: ensure example files are deleted
      file:
        state: absent
        path: "{{ item }}"
      with_items: "{{ delete_list.stdout_lines }}"
      notify: restart datadog-agent

  become: true

- name: configure datadog agent
  include: configured.yml

- name: ensure datadog-agent is running
  service:
    name: datadog-agent
    state: started
    enabled: yes
  become: yes